---
Name: Postmark
---
SiteConfig:
  extensions:
    - PostmarkExtension
PostmarkAdmin:
  member_class: 'Member'
Injector:
  MySQLDatabase:
    class: 'PostmarkMySQLDatabase'
    properties:
      connector: %$MySQLiConnector
      schemaManager: %$PostmarkMySQLSchemaManager
      queryBuilder: %$MySQLQueryBuilder
Director:
  rules:
    'postmark-notifier//$Action/$ID/$OtherID'          : 'PostmarkNotifier',
    'postmark-attachments//$Action/$ID/$OtherID'       : 'PostmarkAttachments'