---
Name: Postmark
---
SiteConfig:
  extensions:
    - PostmarkExtension
PostmarkAdmin:
  member_class: 'Member'
Director:
  rules:
    'postmark-notifier//$Action/$ID/$OtherID'  : 'PostmarkNotifier',
    'postmark-attachments//$Action/$ID/$OtherID'       : 'PostmarkAttachments'